USE [master]
GO

/****** Object:  Database [Academy]    Script Date: 07.11.2023 0:40:09 ******/
CREATE DATABASE [Academy]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Academy', FILENAME = N'H:\Віталій\SQL\Academy.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Academy_log', FILENAME = N'H:\Віталій\SQL\Academy_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Academy].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Academy] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Academy] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Academy] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Academy] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Academy] SET ARITHABORT OFF 
GO

ALTER DATABASE [Academy] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Academy] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Academy] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Academy] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Academy] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Academy] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Academy] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Academy] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Academy] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Academy] SET  ENABLE_BROKER 
GO

ALTER DATABASE [Academy] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Academy] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Academy] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Academy] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Academy] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Academy] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Academy] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Academy] SET RECOVERY FULL 
GO

ALTER DATABASE [Academy] SET  MULTI_USER 
GO

ALTER DATABASE [Academy] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Academy] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Academy] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Academy] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [Academy] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Academy] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [Academy] SET QUERY_STORE = ON
GO

ALTER DATABASE [Academy] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO

ALTER DATABASE [Academy] SET  READ_WRITE 
GO


